create table if not exists public.central_pro_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists central_pro_push_subscriptions_user_id_idx on public.central_pro_push_subscriptions(user_id);
alter table public.central_pro_push_subscriptions enable row level security;
-- A tabela é acessada somente pelo servidor usando SUPABASE_SERVICE_ROLE_KEY.
